apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: default
  labels:
    app: postgres
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /var/lib/postgresql/data
  capacity:
    storage: 5G
